export const ADDTOCARTURL:string="http://localhost:8080/addfoodtocart"
export const REMOVEFROMCARTURL:string="http://localhost:8080/removefoodfromcart"
export const GETFOODFROMCARTURL:string="http://localhost:8080/getfoodsfromcart"
export const REGISTERUSERURL:string="http://localhost:8080/register-user"
export const LOGINUSERURL:string="http://localhost:8080/login-user"
export const GOOGLELOGINURL:string="http://localhost:8080/google-login"
export const REGISTERRESTAURANTURL:string="http://localhost:8080/register-restaurant"
export const GETALLFOODSURL:string="http://localhost:8080/getallfoods"
export const ADDFOODURL:string="http://localhost:8080/food"
export const GETFOODSFROMRESTAURANTURL:string="http://localhost:8080/fooditems"
export const DELETEFOODURL:string="http://localhost:8080/updatefooditem"
export const LOGINRESTAURANTURL:string="http://localhost:8080/login-restaurant"
export const SEARCHFOODURL:string="http://localhost:8080/searchbyfood"
export const FETCHRECOMMENDEDFOODURL:string="http://localhost:8080/fetchTheCommendedFood"
export const FETCHCITIESURL:string="http://localhost:8080/fetchTheResaturantLocation"
export const EDITUSERPROFILEURL:string="http://localhost:8080/editUserProfile"
export const FETCHBYCITYURL:string="http://localhost:8080/fetchRestaurantByCities"
export const FETCHIMAGEURL:string="http://localhost:8080/downloadFile/"
export const GETRESTAURANTBYIDURL:string="http://localhost:8080/getrestaurantbyrestaurantid"
export const GETFOODBYIDURL:string="http://localhost:8080/getfoodbyfoodid"
export const GETALLRESTAURANT:string="http://localhost:8080/getRestaurantStatus"
export const CHANGERESTAURANTSTATUS:string="http://localhost:8080/changeRestaurantStatus"
export const SEARCHKEYWORDURL:string="http://localhost:8080/searchbykeyword"
export const GETSTATISTICSCOUNT:string="http://localhost:8080/getStatisticsCount"
export const GETTOPTENFOOD:string="http://localhost:8080/getTopTenFoods"
export const GETTOPFIVEERESTAURANT:string="http://localhost:8080/getTopFiveRestaurant"
export const GETLEASTFIVEERESTAURANT:string="http://localhost:8080/getLeastFiveRestaurant"
export const GETEDITUSERDETAILS:string="http://localhost:8080/getEditUserProfileDetails"
export const ORDERFOODURL:string="http://localhost:8080/placeorder"



